
###################################################
#
# file: Makefile
#
# @Author:   Iacovos G. Kolokasis
# @Version:  10-02-2022
# @email:    kolokasis@csd.uoc.gr
#
# Makefile
#
####################################################

CC = gcc
CFLAGS = -Wall -ansi -pedantic -g
all:	
	gcc  src/grid.h src/sudoku.h src/sudoku.c src/grid.c

clean:
	-rm -rf src/grid.h.gch
	-rm -rf src/sudoku.h.gch
